# Generated by Django 4.2.2 on 2023-07-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commented_on', to='ads_app.comment'),
        ),
    ]
